site_name: iOS Club 教學網

site_url: https://tutorial.iosclub.tw

nav:
  - Home: index.md
  - 學習程式設計 1:
      - swift-learning-1/index.md
      - 指令:
          - swift-learning-1/1-commands/index.md
          - 發出指令: swift-learning-1/1-commands/1-issuing-commands.md
          - 加入新指令: swift-learning-1/1-commands/2-adding-a-new-command.md
          - 切換開關: swift-learning-1/1-commands/3-toggling-a-switch.md
          - 傳送門練習: swift-learning-1/1-commands/4-portal-practice.md
          - 尋找並修正程式錯誤: swift-learning-1/1-commands/5-finding-and-fixing-bugs.md
          - 除錯練習: swift-learning-1/1-commands/6-bug-squash-practice.md
          - 最短路線: swift-learning-1/1-commands/7-the-shortest-route.md
      - 函數:
          - swift-learning-1/2-functions/index.md
          - 組合新的動作: swift-learning-1/2-functions/1-composing-a-new-behavior.md
          - 建立新函數: swift-learning-1/2-functions/2-creating-a-new-function.md
          - 收集、切換、重複: swift-learning-1/2-functions/3-collect-toggle-repeat.md
          - 全面而徹底: swift-learning-1/2-functions/4-across-the-board.md
          - 嵌套模式: swift-learning-1/2-functions/5-nesting-patterns.md
          - 嵌入式階梯: swift-learning-1/2-functions/6-slotted-stairways.md
          - 尋寶: swift-learning-1/2-functions/7-treasure-hunt.md
      - For 迴圈:
          - swift-learning-1/3-for/index.md
          - 使用迴圈: swift-learning-1/3-for/1-using-loops.md
          - 迴圈每一側: swift-learning-1/3-for/2-looping-all-the-sides.md
          - 走到邊緣再返回: swift-learning-1/3-for/3-to-the-edge-and-back.md
          - 迴圈跳躍者: swift-learning-1/3-for/4-loop-jumper.md
          - 拓展技能: swift-learning-1/3-for/5-branch-out.md
          - 寶石農場: swift-learning-1/3-for/6-gem-farm.md
          - 橫掃四方: swift-learning-1/3-for/7-four-stash-sweep.md
      - 條件碼:
          - swift-learning-1/4-conditional-code/index.md
          - 檢查開關: swift-learning-1/4-conditional-code/1-checking-for-switches.md
          - 使用 else if: swift-learning-1/4-conditional-code/2-using-else-if.md
          - 迴圈條件碼: swift-learning-1/4-conditional-code/3-looping-conditional-code.md
          - 符合條件時往上爬: swift-learning-1/4-conditional-code/4-conditional-climb.md
          - 定義更聰明的函數: swift-learning-1/4-conditional-code/5-defining-smarter-functions.md
          - 困在裡面: swift-learning-1/4-conditional-code/6-boxed-in.md
          - 決定樹: swift-learning-1/4-conditional-code/7-decision-tree.md
      - 邏輯運算子:
          - swift-learning-1/5-logical-operators/index.md
          - 使用 NOT 運算子: swift-learning-1/5-logical-operators/1-using-the-not-operator.md
          - NOT 螺旋: swift-learning-1/5-logical-operators/2-spiral-of-not.md
          - 檢查這個 AND 那個: swift-learning-1/5-logical-operators/3-checking-this-and-that.md
          - 檢查這個 OR 那個: swift-learning-1/5-logical-operators/4-checking-this-or-that.md
          - 邏輯迷宮: swift-learning-1/5-logical-operators/5-logical-labyrinth.md
      - While 迴圈:
          - swift-learning-1/6-while-loop/index.md
          - 當...時執行程式碼: swift-learning-1/6-while-loop/1-running-code-while.md
          - 建立更聰明的 While 迴圈: swift-learning-1/6-while-loop/2-creating-smarter-while-loops.md
          - 選擇正確的工具: swift-learning-1/6-while-loop/3-choosing-the-correct-tool.md
          - 4 乘 4: swift-learning-1/6-while-loop/4-four-by-four.md
          - 轉身: swift-learning-1/6-while-loop/5-turned-around.md
          - 富饒之地: swift-learning-1/6-while-loop/6-land-of-bounty.md
          - 嵌套迴圈: swift-learning-1/6-while-loop/7-nesting-loops.md
          - 隨機矩形: swift-learning-1/6-while-loop/8-random-rectangles.md
          - 每次都右轉: swift-learning-1/6-while-loop/9-youre-always-right.md
      - 演算法:
          - swift-learning-1/7-algorithms/index.md
          - 右手規則: swift-learning-1/7-algorithms/1-the-right-hand-rule.md
          - 調整你的演算法: swift-learning-1/7-algorithms/2-adjusting-your-algorithm.md
          - 征服迷宮: swift-learning-1/7-algorithms/3-conquering-a-maze.md
          - 左轉還是右轉？: swift-learning-1/7-algorithms/4-which-way-to-turn.md
          - 向左走，向右走: swift-learning-1/7-algorithms/5-roll-right-roll-left.md
  - 學習程式設計 2:
      - swift-learning-2/index.md
      - 變數:
          - swift-learning-2/1-variables/index.md
          - 持續追蹤: swift-learning-2/1-variables/1-keeping-tracks.md
          - 加大數值: swift-learning-2/1-variables/2-bump-up-the-value.md
          - 遞增數值: swift-learning-2/1-variables/3-incrementing-the-value.md
          - 尋找七顆寶石: swift-learning-2/1-variables/4-seeking-seven-gems.md
          - 三顆寶石，四個開關: swift-learning-2/1-variables/5-three-gems-four-switches.md
          - 檢查相等值: swift-learning-2/1-variables/6-checking-for-equal-values.md
          - 計算開關數量: swift-learning-2/1-variables/7-round-up-the-switches.md
          - 收集總數: swift-learning-2/1-variables/8-collect-the-total.md
      - 類型:
          - swift-learning-2/2-types/index.md
          - 關閉傳送門: swift-learning-2/2-types/1-deactivating-a-portal.md
          - 開啟和關閉傳送門: swift-learning-2/2-types/2-portal-on-and-off.md
          - 開啟和關閉正確的傳送門: swift-learning-2/2-types/3-setting-the-right-portal.md
          - 世界的角落: swift-learning-2/2-types/4-corners-of-the-world.md
          - 遍布隨機的寶石: swift-learning-2/2-types/5-random-gems-everywhere.md
      - 初始化:
          - swift-learning-2/3-initialization/index.md
          - 初始化你的專家: swift-learning-2/3-initialization/1-initializing-your-expert.md
          - 訓練你的專家: swift-learning-2/3-initialization/2-train-your-expert.md
          - 使用不同類型的實例: swift-learning-2/3-initialization/3-using-instances-of-different-types.md
          - 需要兩人合作: swift-learning-2/3-initialization/4-it-takes-two.md
      - 參數:
          - swift-learning-2/4-parameters/index.md
          - 繼續前行: swift-learning-2/4-parameters/1-moving-further-forward.md
          - 歸納函數: swift-learning-2/4-parameters/2-generalizing-a-function-parameters.md
          - 上下轉動: swift-learning-2/4-parameters/3-crack-up-and-down.md
          - 置於特定位置: swift-learning-2/4-parameters/4-placing-at-a-specific-location.md
          - 渡過河流: swift-learning-2/4-parameters/5-rivers-to-cross.md
          - 放置兩個角色: swift-learning-2/4-parameters/6-placing-two-characters.md
          - 兩個專家: swift-learning-2/4-parameters/7-two-experts.md
          - 雙峰: swift-learning-2/4-parameters/8-twin-peaks.md
      - 構建世界:
          - swift-learning-2/5-world-building/index.md
          - 結合世界: swift-learning-2/5-world-building/1-uniting-worlds.md
          - 連接並解決: swift-learning-2/5-world-building/2-connect-and-solve.md
          - 製作你自己的傳送門: swift-learning-2/5-world-building/3-making-your-own-portals.md
          - 到達階梯: swift-learning-2/5-world-building/4-reach-for-the-stairs.md
          - 浮動的島嶼: swift-learning-2/5-world-building/5-floating-islands.md
          - 建立迴圈: swift-learning-2/5-world-building/6-build-a-loop.md
          - 你自己的關卡: swift-learning-2/5-world-building/7-a-puzzle-of-your-own.md
      - 陣列:
          - swift-learning-2/6-arrays/index.md
          - 儲存資訊: swift-learning-2/6-arrays/1-storing-information.md
          - 探索反覆運算: swift-learning-2/6-arrays/2-iteration-exploration.md
          - 堆疊磚塊: swift-learning-2/6-arrays/3-stacking-blocks.md
          - 依序排列: swift-learning-2/6-arrays/4-getting-in-order.md
          - 附加到陣列: swift-learning-2/6-arrays/5-appending-to-an-array.md
          - 島嶼建構者: swift-learning-2/6-arrays/6-island-builder.md
          - 附加到移除的值: swift-learning-2/6-arrays/7-appending-removed-values.md
          - 修正索引越界錯誤: swift-learning-2/6-arrays/8-fixing-array-out-of-bounds-errors.md
          - 產生地形: swift-learning-2/6-arrays/9-generate-a-landscape.md
          - 隨機化的陸地: swift-learning-2/6-arrays/10-randomized-lands.md
          - 另一種建立陣列的方法: swift-learning-2/6-arrays/11-another-way-to-create-an-array.md
          - 陣列的藝術: swift-learning-2/6-arrays/12-the-art-of-the-array.md
          - 創造世界: swift-learning-2/6-arrays/13-world-creation.md

theme:
  logo: assets/images/favicon.png
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.expand
    - content.code.copy
  language: zh-TW
  font:
    text: "Noto Serif TC"
    code: "JetBrains Mono"
  palette:

   - scheme: default
     primary: light blue
     toggle:
       icon: material/brightness-7
       name: Switch to dark mode
   - scheme: slate
     primary: blue grey
     toggle:
       icon: material/brightness-4
       name: Switch to system preference
  icon:
    logo: material/apple-ios

copyright: Copyright &copy; 2016 - 2025 Feng Chia University iOS Club

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list
extra:
  social:
    - icon: material/web
      link: https://iosclub.tw
    - icon: material/mail
      link: mailto:iosclub@mail.iosclub.tw
